stages:
- stage : validate
  jobs:
    - job: validate
      continueOnError : false
      steps:
        - task: TerraformInstaller@0
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV3@3
          displayName : 'init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'azure-spn'
            backendAzureRmResourceGroupName: 'resourcegroup-tfstate'
            backendAzureRmStorageAccountName: 'terraformtfstateskips'
            backendAzureRmContainerName: 'tfcontainer'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTaskV3@3
          displayName : 'validate'
          inputs:
              provider: 'azurerm'
              command: 'validate'
- stage : deploy
  jobs:
        - deployment: deploy_terraform
          continueOnError : false
          environment: 'dev'
          strategy:
            runOnce:
              deploy:
                steps:
                  - checkout: self
                  - task: TerraformInstaller@0
                    displayName : 'install'
                    inputs:
                      terraformVersion: 'latest'
                    
                  - task: TerraformTaskV3@3
                    displayName : 'init'
                    inputs:
                      provider: 'azurerm'
                      command: 'init'
                      workingDirectory: '$(System.DefaultWorkingDirectory)/ devops/terraform/'
                      backendServiceArm: 'azure-spn'
                      backendAzureRmResourceGroupName: 'resourcegroup-tfstate'
                      backendAzureRmStorageAccountName: 'terraformtfstateskips'
                      backendAzureRmContainerName: 'tfcontainer'
                      backendAzureRmKey: 'terraform.tfstate'
                  
                  - task: TerraformTaskV3@3
                    displayName : 'apply'
                    inputs:
                      provider: 'azurerm'
                      command: 'apply'
                      workingDirectory: '$(System.DefaultWorkingDirectory)/ devops/terraform/'
                      environmentServiceNameAzureRM: 'azure-spn'