# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Date:yy)$(DayOfYear)$(Rev:rrrr)

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Versioning

stages:
  - stage: build
    displayName: BuildArtifacts
    jobs:
      - job: Test Terraform

- task: TerraformInstaller@0
                inputs:
                  terraformVersion: 'latest'

              - task: TerraformCLI@0
                inputs:
                  command: 'init'
                  allowTelemetryCollection: true

              - task: TerraformCLI@0
                inputs:
                  command: 'plan'
                  allowTelemetryCollection: true
              - task: TerraformCLI@0
                inputs:
                  command: 'apply'
                  runAzLogin: true
                  allowTelemetryCollection: true