# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  subscription: d079a55f-f2f8-4eaa-9a72-f0c00fce0855
  resourceGroup: resourcegroup-tfnew
  storageAccount: tfstraccunt1
  container: tfstate
  tfstateFile: terraform.tfstate
  anyTfChanges: false

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
  displayName: "Install Terraform"

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
    backendType: 'selfConfigured'
    allowTelemetryCollection: true
    backendAzureRmResourceGroupName: '$(resourceGroup)'
    backendAzureRmStorageAccountName: '$(storageAccount)'
    backendAzureRmContainerName: '$(container)'
    backendAzureRmKey: '$(tfstateFile)'
  displayName: "Initiallize Terraform"
  
