# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Date:yy)$(DayOfYear)$(Rev:rrrr)

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Versioning

stages:
  - stage: build
    displayName: BuildArtifacts
    jobs:
      - job: BuildArtifact
        displayName: Build Artifact
        steps:
          
        
        - task: TerraformInstaller@0
          inputs:
            terraformVersion: 'latest'
          displayName: "Install Terraform"

      
        - task: TerraformCLI@0
          inputs:
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
            backendType: 'selfConfigured'
            allowTelemetryCollection: true
          displayName: "Initiallize Terraform"



        - task: TerraformCLI@0
          inputs:
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
            allowTelemetryCollection: true
          displayName: "validate Terraform Script"


  - stage: deploy
    displayName: "Deploy Artifacts"
    dependsOn: "Build"
    jobs:
      - job: 
        displayName: "Deploy Artifact"
        steps:
        - task: TerraformCLI@0
          inputs:
           command: 'init'
           workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
           allowTelemetryCollection: true
          displayName: "Initiallize Teraform"

        - task: TerraformCLI@0
          inputs:
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Env'
            commandOptions: '-auto-approve'
            allowTelemetryCollection: true
          displayName: "Deploy Terraform Script"
