# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Date:yy)$(DayOfYear)$(Rev:rrrr)

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
    - group: Versioning
stages:
  - stage: build
    jobs:
      - job: InitializeTerraform
        displayName: Initailize
        steps:
        - task: TerraformInstaller@0
          inputs:
            terraformVersion: 'latest'
        - task: TerraformCLI@0
         
          inputs:
             
            command: 'init'
            allowTelemetryCollection: true
            workingDirectory: 'StorageAccount-Terraform'

            backendServiceArm: 'd079a55f-f2f8-4eaa-9a72-f0c00fce0855'

            backendAzureRmResourceGroupName: 'resourcegroup-tfnew'

            backendAzureRmStorageAccountName: 'tfstraccunt1'

            backendAzureRmContainerName: 'tfstate'

            backendAzureRmKey: 'tf/terraform.tfstate'
        
        - task: TerraformCLI@0
          inputs:
            command: 'validate'
            allowTelemetryCollection: true
        
         
     

      

      

             
         